### ISSUE TITLE
Linux: Download required dependencies

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/swiftly#32]
See https://www.swift.org/download/#linux

**Comment by MahdiBM** [comment]
Just want to mention that I think this is an important feature to have so I personally can start advising users to use Swiftly over https://swiftlang.xyz.

If I were to mention a second-important feature to make sure there is no longer a reason to advise https://swiftlang.xyz, it would be #42 (making sure users don't have to manually deal with PATH).

Just throwing my thoughts out here for what they're worth since I see Swiftly is approaching a release and @0xTim is hopeful we can start using Swiftly in the Vapor Discord server.

**Comment by patrickfreed** [comment]
Your feedback is much appreciated, thanks for providing it! And yeah I agree, I think this and #42 are probably worth having for the initial release to help ensure good first experiences with swiftly. Regarding the dependencies, the [design](https://github.com/swift-server/swiftly/blob/main/DESIGN.md) for swiftly has a plan for a more complicated approach to system dependencies that involves trying to detect them in case a user installed them manually, but I think for an initial release at least (if not indefinitely), just handing it in the install script is probably fine.

Regarding the PATH, `~/.local/bin` is already on the PATH for most distributions, so users shouldn't _have_ to mess with it unless they configure it otherwise. That said, sometimes it doesn't exist on the path (e.g. for the root user), and sometimes users will want to configure other directories, and in either case #42 is very useful.

**Comment by adam-fowler** [comment]
Can't remember what that more complex plan was for installing dependencies. Shouldn't we leave that to `apt-get` or `yum`. We can easily add to the install script the dependency installation. We can scrap the dependencies from the docker image scripts in swift-docker.
