### ISSUE TITLE
Swift REPL not working

### ISSUE THREAD

**Issue by marius-se** [swift-server/swiftly#78]
I just Swift 5.9.0 using Swiftly on a fresh Fedora 38 and it seems like `swift repl` isn't working because of a missing Python version.

`python3 --version` tells me I'm on 3.11.5 and `swift repl` returns the following error:
```
/home/marius/.local/share/swiftly/toolchains/5.9.0/usr/bin/lldb: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```

I suspect installing Python 3.9 would fix the issue, but is there a way to get this out of the box with Swiftly?

**Comment by patrickfreed** [comment]
Unfortunately, with external system dependency issues like this, there isn't much swiftly can do. At the moment, `swiftly-install.sh` scrapes the list of dependencies to install from the Dockerfile associated with that platform. For Fedora 38, I imagine the RHEL dockerfile would be used: https://github.com/apple/swift-docker/blob/main/nightly-main/rhel-ubi/9/Dockerfile#L6-L18. That list does include `python3-devel`, but it looks like that package on Fedora 38 installs Python 3.11.5, as you're seeing: https://packages.fedoraproject.org/pkgs/python3.11/python3-devel/

To work around this, I'd recommend just manually installing the required Python version, since unfortunately, I don't think there's anything swiftly or swiftly-install.sh can do for platforms other than the ones that have dockerfiles explicitly provided for them.

**Comment by marius-se** [comment]
I see, thanks!
